import type { getCollectionsForPerkType } from '@utils/roguelite'

export interface ParsedParams {
    perkType: string | null
    collections: ReturnType<typeof getCollectionsForPerkType>
    levelRequired: string | null
    rarity: string | null
    rarities: string[] | null
    seed: string | null
    perkAmount: number | null
    userLevel: number | undefined
    // Filtros específicos para magias
    element: string | null
    spellLevel: number | null
    execution: string | null
    // Filtros específicos para armas
    ignoreWeaponLevelWeight: boolean
    // Filtros específicos para itens
    itemKind: string | null
    itemKinds: string[] | null
    // Filtros específicos para habilidades
    skillTypes: string[] | null
}

export interface QueryMetadata {
    collections: string[]
    filters: {
        perkType: string | null
        levelRequired: string | null
        rogueliteRarity: string | null
    }
    totalItems: number
    seed?: string
    perkAmount?: number
    selectedFrom?: number
    autoGenerated?: boolean
}