import type { Expertises } from '@models';

export const EXPERTISE_WEIGHTS: Partial<Record<keyof Expertises, number>> = {
    'Atletismo': 75,
    'Diplomacia': 55,
    'Intimidação': 50,
    'Luta': 65,
    'Pontaria': 70,
    'Conhecimento': 45,
    'Concentração': 50,
    'Engenharia': 40,
    'Medicina': 50,
    'Sobrevivência': 60,
    'Furtividade': 65,
    'Percepção': 80,
    'Reflexos': 75,
    'RES Física': 70,
    'RES Mágica': 65,
    'RES Mental': 60,
    'Agilidade': 70,
    'Sorte': 30,
    'Competência': 55,
    'Vontade': 65,
    'Comunicação': 50,
    'Condução': 45,
    'Controle': 60,
    'Criatividade': 50,
    'Culinária': 25,
    'Eficácia': 55,
    'Enganação': 45,
    'Fortitude': 70,
    'Força': 65,
    'Interrogação': 40,
    'Intuição': 55,
    'Investigação': 50,
    'Ladinagem': 55,
    'Liderança': 45,
    'Magia': 75,
    'Persuasão': 50,
    'Tecnologia': 60,
    'Tática': 55
}